In [25]:
x=[[1,2,3,4,5],[5,6,7,8,9]]
y=[1,4,9,4,2]

In [26]:
import numpy as np
x=np.array(x)
y=np.array(y)
x_transpose = np.transpose(x)
data = np.column_stack((x_transpose,y))
correlation_matrx=np.corrcoef(data,rowvar=False)
print(correlation_matrx)

[[1.         1.         0.10259784]
 [1.         1.         0.10259784]
 [0.10259784 0.10259784 1.        ]]


In [27]:
x=np.array(x)
y=np.array(y)
x_inter= np.column_stack((np.ones(len(y)), x[0]))
theta=np.linalg.inv(x_inter.T @ x_inter) @ (x_inter.T @ y)
y_pred_train = x_inter @ theta
print(theta)

[ 8.36136715e-15 -2.03309591e-15  1.00000000e+00]


In [28]:
residuals = y - y_pred_train
SSE = np.sum(residuals ** 2)
SSR = np.sum((y_pred_train - np.mean(y)) ** 2)
SST = SSE + SSR
R2 = SSR / SST

# Step 7: Display results
print("\nRegression Parameters (theta):")
print(theta)
print("\nSSE (Sum of Squared Errors):", SSE)
print("SSR (Sum of Squared Regression):", SSR)
print("SST (Total Sum of Squares):", SST)
print("R-squared (R2):", R2)


Regression Parameters (theta):
[ 8.36136715e-15 -2.03309591e-15  1.00000000e+00]

SSE (Sum of Squared Errors): 7.619533527819889e-28
SSR (Sum of Squared Regression): 37.999999999999986
SST (Total Sum of Squares): 37.999999999999986
R-squared (R2): 1.0
